env:
  es6: true
  browser: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  sourceType: module
  ecmaVersion: 2022

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  no-console:
    - error
